name: scratch-build
on: push
jobs:
  build:

    strategy:
      matrix:
          os: [ 'el7', 'el8', 'el9', 'd10', 'u18', 'u20' ]
 
    runs-on: ubuntu-latest

    steps:
      - name: Check out Repo
        uses: actions/checkout@v3
      - name: Run Docker Run!
        run: curl -s https://raw.githubusercontent.com/perfsonar/docker-oneshot-builder/main/build | sh -s - . ${{ matrix.os }}

